language: objective-c  #1
osx_image: xcode10.2 #2

install:
  - gem install xcpretty

jobs:
  include:
    - script: xcodebuild clean build test -project FizzBuzz.xcodeproj -scheme FizzBuzz -destination "platform=iOS Simulator,name=iPhone XR,OS=12.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - script: swiftlint
